### ISSUE TITLE
Example files

### ISSUE THREAD

**Issue by aschleife** [Randolph-zeng/MS-SPIN-PROJECT#9]
Zhongshen,

Would it be possible to include your example files (all the structures that were used on the last production version of this code under your DigitalOcean account) here, too?

I successfully installed it, but it does not have many structures built in. Best,

  Andre

**Comment by Randolph-zeng** [comment]
Hi professor, are you able to attach a screenshot or copy the logs from the browser consoles to here? I am not very sure about the meaning of not many structures right now :).

**Comment by aschleife** [comment]
Haha, well, I am not sure if you see the problem there. What I mean is, that if you go here:

http://104.131.18.56:3000/Project.html

You just see one entry "LAO". In your version we had a lot more. Do those still exist? Also, if you dont like chatting here, feel free to email me. Thanks for your help and all the best,

  Andre

**Comment by Randolph-zeng** [comment]
Oops, sorry professor that I did not write it in the docs. The entries should be generated dynamically. If you put xyz files and vesta files into the vesta_files folder under the frontend directory, entries will be generated automatically for you(granted the data files follows the format we agree with before).
I will close this issue now and wish you have a great day!

**Comment by aschleife** [comment]
Sorry, one more follow-up: Would you mind putting the total set of files in your latest/most complete vesta_files folder in an "examples" folder here on Github? This way I can directly start from our last status. Thanks so much, I appreciate your help!

**Comment by Randolph-zeng** [comment]
sure professor, I have added them back, you can check to see if they functions as expected!

**Comment by aschleife** [comment]
Excellent! Thanks very much, I appreciate the quick help!

**Comment by Randolph-zeng** [comment]
you are welcome!
